import { AgentId, AgentProfile } from '../types';

export const AGENT_PROFILES: Record<AgentId, AgentProfile> = {
  technical: {
    id: 'technical',
    name: 'Dr. Marcus Vance',
    roleTitle: 'Principal Systems & Technical Specialist',
    domain: 'Technical Depth & Architecture',
    avatarBg: 'bg-gradient-to-br from-blue-600 to-cyan-500',
    accentColor: 'text-blue-400',
    borderColor: 'border-blue-500/40',
    speechPitch: 0.9,
    speechRate: 1.0,
    mission: 'Examines technical mastery, system design principles, distributed state, concurrency, and hard coding trade-offs.',
  },
  culture: {
    id: 'culture',
    name: 'Elena Rostova',
    roleTitle: 'Head of People, Culture & Leadership',
    domain: 'Communication, Teamwork & Ethics',
    avatarBg: 'bg-gradient-to-br from-purple-600 to-pink-500',
    accentColor: 'text-purple-400',
    borderColor: 'border-purple-500/40',
    speechPitch: 1.2,
    speechRate: 1.02,
    mission: 'Evaluates empathy, honest self-reflection, conflict handling, and STAR-format behavioral structure.',
  },
  hiring_manager: {
    id: 'hiring_manager',
    name: 'David Sterling',
    roleTitle: 'Engineering Director / Hiring Manager',
    domain: 'Business ROI, Execution & Delivery',
    avatarBg: 'bg-gradient-to-br from-emerald-600 to-teal-500',
    accentColor: 'text-emerald-400',
    borderColor: 'border-emerald-500/40',
    speechPitch: 1.0,
    speechRate: 1.05,
    mission: 'Determines if this candidate is genuinely worth hiring: focus on business value, delivery velocity, and team leverage.',
  },
  skeptic: {
    id: 'skeptic',
    name: 'Rachel Zane',
    roleTitle: 'Contradiction & Red-Flag Auditor',
    domain: 'Fact-Checking & Anti-Exaggeration',
    avatarBg: 'bg-gradient-to-br from-amber-600 to-rose-600',
    accentColor: 'text-amber-400',
    borderColor: 'border-amber-500/40',
    speechPitch: 0.85,
    speechRate: 1.08,
    mission: 'Hunts for discrepancies between resume claims and actual transcript answers, uncovers buzzwords, and tests integrity.',
  }
};
