import React, { useEffect, useState } from 'react';
import { FinalConsensusReport } from '../types';
import { AGENT_PROFILES } from '../lib/agents';
import { 
  Award, 
  CheckCircle, 
  AlertTriangle, 
  Download, 
  RotateCcw, 
  Share2, 
  Star, 
  Check, 
  Quote, 
  Scale, 
  HelpCircle,
  Sparkles 
} from 'lucide-react';
import confetti from 'canvas-confetti';

interface FinalDecisionReportProps {
  report: FinalConsensusReport;
  onRestart: () => void;
}

export const FinalDecisionReport: React.FC<FinalDecisionReportProps> = ({
  report,
  onRestart,
}) => {
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    if (report.finalRecommendation === 'Strong Hire' || report.finalRecommendation === 'Hire') {
      try {
        confetti({
          particleCount: 90,
          spread: 80,
          origin: { y: 0.6 }
        });
      } catch {
        // Confetti fallback
      }
    }
  }, [report.finalRecommendation]);

  const getDecisionBadge = (decision: FinalConsensusReport['finalRecommendation']) => {
    switch (decision) {
      case 'Strong Hire':
        return 'text-emerald-400 bg-emerald-950/80 border-emerald-500/60 shadow-emerald-500/20';
      case 'Hire':
        return 'text-indigo-400 bg-indigo-950/80 border-indigo-500/60 shadow-indigo-500/20';
      case 'Leaning No Hire':
        return 'text-amber-400 bg-amber-950/80 border-amber-500/60 shadow-amber-500/20';
      default:
        return 'text-rose-400 bg-rose-950/80 border-rose-500/60 shadow-rose-500/20';
    }
  };

  const handleCopyMarkdown = () => {
    const md = `# Multi-Agent Committee Decision: ${report.candidateName}
**Target Role**: ${report.targetRole}
**Final Recommendation**: ${report.finalRecommendation} (Confidence: ${report.overallConfidence}%)

## Executive Decision Rationale
${report.decisionRationale}

## Evidence-Weighting Mechanism (Non-Simple Averaging)
${report.evidenceWeightingExplanation}

## Key Strengths
${report.keyStrengths.map(s => `- **${s.title}**: ${s.detail}\n  > *Quote*: ${s.supportingQuote}`).join('\n\n')}

## Critical Concerns
${report.criticalConcerns.map(c => `- **${c.title}** [${c.severity.toUpperCase()}]: ${c.detail}\n  > *Quote*: ${c.supportingQuote}`).join('\n\n')}

## Unresolved Disagreements Between Agents
${report.unresolvedDisagreements.length > 0 
  ? report.unresolvedDisagreements.map(d => `- **${d.topic}**\n  - ${d.agentAPerspective.agentId}: ${d.agentAPerspective.point}\n  - ${d.agentBPerspective.agentId}: ${d.agentBPerspective.point}\n  - *Impact*: ${d.impactOnDecision}`).join('\n\n')
  : 'None. Complete consensus achieved across all dimensions.'}

## Individual Agent Vote Evolution
${Object.entries(report.individualAgentFinalVotes).map(([agentId, vote]) => `- **${agentId}**: ${vote.initialStance} → **${vote.finalStance}** (Changed mind: ${vote.changedMind ? 'Yes' : 'No'})\n  - ${vote.finalVerdict}`).join('\n')}

---
*Generated by Multi-Agent AI Hiring Committee Simulator*`;

    navigator.clipboard.writeText(md);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  const handleDownloadJSON = () => {
    const dataStr = "data:text/json;charset=utf-8," + encodeURIComponent(JSON.stringify(report, null, 2));
    const downloadAnchor = document.createElement('a');
    downloadAnchor.setAttribute("href", dataStr);
    downloadAnchor.setAttribute("download", `committee-report-${report.candidateName.toLowerCase().replace(/\s+/g, '-')}.json`);
    document.body.appendChild(downloadAnchor);
    downloadAnchor.click();
    downloadAnchor.remove();
  };

  return (
    <div className="max-w-6xl mx-auto p-4 md:p-6 space-y-6 text-slate-100 animate-in fade-in duration-300">
      {/* Top Banner */}
      <div className="bg-gradient-to-r from-boardroom-900 via-boardroom-850 to-indigo-950/60 border border-slate-800 rounded-3xl p-6 md:p-8 shadow-2xl relative overflow-hidden">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-6 relative z-10">
          <div className="space-y-2">
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-emerald-500/10 text-emerald-400 border border-emerald-500/30 text-xs font-semibold">
              <Award className="w-3.5 h-3.5" /> Step 4: Final Committee Consensus Report
            </div>
            <h1 className="text-3xl md:text-4xl font-extrabold text-white tracking-tight">
              {report.candidateName}
            </h1>
            <p className="text-slate-400 text-sm font-medium">
              Evaluated for: <span className="text-white font-semibold">{report.targetRole}</span>
            </p>
          </div>

          {/* Verdict & Confidence */}
          <div className="flex items-center gap-4">
            <div className="text-center px-5 py-3 rounded-2xl bg-boardroom-900 border border-slate-800">
              <span className="text-[10px] text-slate-400 uppercase tracking-wider font-bold">Committee Confidence</span>
              <div className="text-2xl md:text-3xl font-black text-white mt-0.5">
                {report.overallConfidence}%
              </div>
            </div>

            <div className={`px-6 py-4 rounded-2xl border text-center shadow-xl ${getDecisionBadge(report.finalRecommendation)}`}>
              <span className="text-[10px] uppercase tracking-wider font-black block opacity-80">Final Verdict</span>
              <span className="text-xl md:text-2xl font-black">{report.finalRecommendation}</span>
            </div>
          </div>
        </div>

        {/* Decision Rationale */}
        <div className="mt-6 pt-5 border-t border-slate-800/80 space-y-2">
          <h4 className="text-xs font-bold uppercase tracking-wider text-slate-400 flex items-center gap-1.5">
            <Star className="w-3.5 h-3.5 text-amber-400" /> Executive Committee Rationale
          </h4>
          <p className="text-sm text-slate-200 leading-relaxed">
            {report.decisionRationale}
          </p>
        </div>

        {/* Evidence Weighting Callout (Satisfying Non-Simple Averaging Rule) */}
        <div className="mt-4 p-4 rounded-2xl bg-indigo-950/40 border border-indigo-500/30 space-y-1.5">
          <div className="flex items-center gap-2 text-xs font-bold text-indigo-300">
            <Scale className="w-4 h-4 text-indigo-400" />
            <span>Reasoned Evidence-Weighting Mechanism (Non-Simple Averaging):</span>
          </div>
          <p className="text-xs text-slate-300 leading-relaxed">
            {report.evidenceWeightingExplanation}
          </p>
        </div>
      </div>

      {/* Strengths and Concerns */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
        {/* Strengths */}
        <div className="bg-boardroom-900 border border-emerald-950/60 rounded-3xl p-6 space-y-4 shadow-xl">
          <h3 className="text-xs font-bold uppercase tracking-wider text-emerald-400 flex items-center gap-2">
            <CheckCircle className="w-4 h-4" /> Evidence-Backed Strengths
          </h3>
          <div className="space-y-3">
            {report.keyStrengths.map((st, i) => (
              <div key={i} className="p-3.5 rounded-2xl bg-boardroom-850 border border-slate-800 space-y-2">
                <span className="font-bold text-xs text-white block">{st.title}</span>
                <p className="text-xs text-slate-300 leading-relaxed">{st.detail}</p>
                {st.supportingQuote && (
                  <div className="flex items-start gap-1.5 text-[11px] text-slate-400 italic bg-boardroom-900 p-2 rounded-xl border border-slate-800">
                    <Quote className="w-3 h-3 text-emerald-400 shrink-0 mt-0.5" />
                    <span>{st.supportingQuote}</span>
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>

        {/* Critical Concerns & Red Flags */}
        <div className="bg-boardroom-900 border border-amber-950/60 rounded-3xl p-6 space-y-4 shadow-xl">
          <h3 className="text-xs font-bold uppercase tracking-wider text-amber-400 flex items-center gap-2">
            <AlertTriangle className="w-4 h-4" /> Red Flags & Critical Concerns
          </h3>
          <div className="space-y-3">
            {report.criticalConcerns.map((cr, i) => (
              <div key={i} className="p-3.5 rounded-2xl bg-boardroom-850 border border-slate-800 space-y-2">
                <div className="flex items-center justify-between">
                  <span className="font-bold text-xs text-white">{cr.title}</span>
                  <span className={`text-[10px] font-bold px-2 py-0.5 rounded-full uppercase border ${
                    cr.severity === 'high'
                      ? 'bg-rose-950 text-rose-400 border-rose-800'
                      : 'bg-amber-950 text-amber-400 border-amber-800'
                  }`}>
                    {cr.severity} risk
                  </span>
                </div>
                <p className="text-xs text-slate-300 leading-relaxed">{cr.detail}</p>
                {cr.supportingQuote && (
                  <div className="flex items-start gap-1.5 text-[11px] text-slate-400 italic bg-boardroom-900 p-2 rounded-xl border border-slate-800">
                    <Quote className="w-3 h-3 text-amber-400 shrink-0 mt-0.5" />
                    <span>{cr.supportingQuote}</span>
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Unresolved Disagreements Section (Mandated by challenge!) */}
      <div className="bg-boardroom-900 border border-purple-500/30 rounded-3xl p-6 space-y-4 shadow-xl">
        <h3 className="text-xs font-bold uppercase tracking-wider text-purple-300 flex items-center gap-2">
          <HelpCircle className="w-4 h-4 text-purple-400" /> Unresolved Disagreements Between Agents
        </h3>
        {report.unresolvedDisagreements.length === 0 ? (
          <p className="text-xs text-slate-400 italic">
            Complete consensus reached. No major unresolved faction disagreements remained after the debate stage.
          </p>
        ) : (
          <div className="space-y-3">
            {report.unresolvedDisagreements.map((dis, idx) => (
              <div key={idx} className="p-4 rounded-2xl bg-boardroom-850 border border-slate-800 space-y-3">
                <span className="font-bold text-xs text-white">{dis.topic}</span>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-3 text-xs">
                  <div className="p-2.5 rounded-xl bg-boardroom-900 border border-slate-800/80">
                    <span className="text-blue-400 font-bold block mb-1">
                      {AGENT_PROFILES[dis.agentAPerspective.agentId]?.name || dis.agentAPerspective.agentId}:
                    </span>
                    <p className="text-slate-300">{dis.agentAPerspective.point}</p>
                  </div>
                  <div className="p-2.5 rounded-xl bg-boardroom-900 border border-slate-800/80">
                    <span className="text-purple-400 font-bold block mb-1">
                      {AGENT_PROFILES[dis.agentBPerspective.agentId]?.name || dis.agentBPerspective.agentId}:
                    </span>
                    <p className="text-slate-300">{dis.agentBPerspective.point}</p>
                  </div>
                </div>
                <div className="text-[11px] text-slate-400 pt-1 border-t border-slate-800/80">
                  <span className="font-semibold text-slate-300">Committee Resolution:</span> {dis.impactOnDecision}
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* Individual Agent Vote Evolution Table */}
      <div className="bg-boardroom-900 border border-slate-800 rounded-3xl p-6 space-y-4 shadow-xl">
        <h3 className="text-xs font-bold uppercase tracking-wider text-slate-300">
          Agent Stance Evolution (Before Debate vs After Debate)
        </h3>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3">
          {Object.entries(report.individualAgentFinalVotes).map(([agentId, vote]) => {
            const agent = AGENT_PROFILES[agentId as keyof typeof AGENT_PROFILES];
            if (!agent) return null;

            return (
              <div key={agentId} className="p-4 rounded-2xl bg-boardroom-850 border border-slate-800 space-y-2">
                <div className="flex items-center gap-2">
                  <div className={`w-7 h-7 rounded-lg ${agent.avatarBg} text-white font-bold flex items-center justify-center text-xs`}>
                    {agent.name.charAt(0)}
                  </div>
                  <div>
                    <span className="text-xs font-bold text-white block">{agent.name}</span>
                    <span className="text-[10px] text-slate-500">{agent.roleTitle.split('/')[0]}</span>
                  </div>
                </div>

                <div className="flex items-center gap-1.5 text-xs font-mono pt-1">
                  <span className="text-slate-400">{vote.initialStance}</span>
                  <span className="text-slate-600">→</span>
                  <span className="font-bold text-white">{vote.finalStance}</span>
                </div>

                {vote.changedMind && (
                  <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded text-[10px] font-bold bg-pink-950/60 text-pink-300 border border-pink-800/60">
                    <Sparkles className="w-2.5 h-2.5" /> Shifted Stance
                  </span>
                )}

                <p className="text-xs text-slate-300 italic pt-1 border-t border-slate-800">
                  "{vote.finalVerdict}"
                </p>
              </div>
            );
          })}
        </div>
      </div>

      {/* Action Footer */}
      <div className="flex flex-wrap items-center justify-between gap-4 pt-4 border-t border-slate-800">
        <button
          onClick={onRestart}
          className="px-5 py-2.5 rounded-xl bg-boardroom-850 border border-slate-700 hover:border-slate-600 text-slate-300 hover:text-white text-xs font-semibold flex items-center gap-2 transition-all"
        >
          <RotateCcw className="w-3.5 h-3.5" />
          <span>Evaluate Another Candidate</span>
        </button>

        <div className="flex items-center gap-3">
          <button
            onClick={handleCopyMarkdown}
            className="px-4 py-2.5 rounded-xl bg-boardroom-850 border border-slate-700 hover:border-indigo-500/50 text-indigo-300 text-xs font-semibold flex items-center gap-2 transition-all"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Share2 className="w-3.5 h-3.5" />}
            <span>{copied ? 'Copied Markdown!' : 'Copy Markdown Summary'}</span>
          </button>

          <button
            onClick={handleDownloadJSON}
            className="px-5 py-2.5 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-bold flex items-center gap-2 shadow-lg shadow-indigo-500/20 transition-all"
          >
            <Download className="w-3.5 h-3.5" />
            <span>Download JSON Report</span>
          </button>
        </div>
      </div>
    </div>
  );
};
