import React, { useEffect } from 'react';
import { CandidateEvaluation } from '../types';
import { INTERVIEWERS } from '../lib/agents';
import { Award, CheckCircle, AlertTriangle, Download, RotateCcw, Share2, Star, Check } from 'lucide-react';
import confetti from 'canvas-confetti';

interface ScorecardReportProps {
  evaluation: CandidateEvaluation;
  onRestart: () => void;
}

export const ScorecardReport: React.FC<ScorecardReportProps> = ({
  evaluation,
  onRestart,
}) => {
  const [copied, setCopied] = React.useState(false);

  useEffect(() => {
    if (evaluation.hiringDecision === 'Strong Hire' || evaluation.hiringDecision === 'Hire') {
      try {
        confetti({
          particleCount: 80,
          spread: 70,
          origin: { y: 0.6 }
        });
      } catch {
        // Confetti fallback
      }
    }
  }, [evaluation.hiringDecision]);

  const getDecisionBadge = (decision: CandidateEvaluation['hiringDecision']) => {
    switch (decision) {
      case 'Strong Hire':
        return 'text-emerald-400 bg-emerald-950/80 border-emerald-500/60 shadow-emerald-500/20';
      case 'Hire':
        return 'text-indigo-400 bg-indigo-950/80 border-indigo-500/60 shadow-indigo-500/20';
      case 'Leaning No Hire':
        return 'text-amber-400 bg-amber-950/80 border-amber-500/60 shadow-amber-500/20';
      default:
        return 'text-rose-400 bg-rose-950/80 border-rose-500/60 shadow-rose-500/20';
    }
  };

  const handleCopyMarkdown = () => {
    const md = `# Candidate Evaluation Report: ${evaluation.candidateName}
**Target Role**: ${evaluation.targetRole}
**Decision**: ${evaluation.hiringDecision} (Overall Score: ${evaluation.overallScore}/100)

## Executive Consensus
${evaluation.consensusSummary}

## Rubric Breakdown
- **${evaluation.dimensions.systemDesign.name}**: ${evaluation.dimensions.systemDesign.score}/10
  - ${evaluation.dimensions.systemDesign.feedback}
- **${evaluation.dimensions.technicalDepth.name}**: ${evaluation.dimensions.technicalDepth.score}/10
  - ${evaluation.dimensions.technicalDepth.feedback}
- **${evaluation.dimensions.communicationSTAR.name}**: ${evaluation.dimensions.communicationSTAR.score}/10
  - ${evaluation.dimensions.communicationSTAR.feedback}
- **${evaluation.dimensions.pragmatismEdgeCases.name}**: ${evaluation.dimensions.pragmatismEdgeCases.score}/10
  - ${evaluation.dimensions.pragmatismEdgeCases.feedback}

## Key Strengths
${evaluation.keyStrengths.map(s => `- ${s}`).join('\n')}

## Growth Areas
${evaluation.growthAreas.map(g => `- ${g}`).join('\n')}

---
*Generated by The Hot Seat Multi-Agent Panel Simulator*`;

    navigator.clipboard.writeText(md);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  const handleDownloadJSON = () => {
    const dataStr = "data:text/json;charset=utf-8," + encodeURIComponent(JSON.stringify(evaluation, null, 2));
    const downloadAnchor = document.createElement('a');
    downloadAnchor.setAttribute("href", dataStr);
    downloadAnchor.setAttribute("download", `evaluation-${evaluation.candidateName.toLowerCase().replace(/\s+/g, '-')}.json`);
    document.body.appendChild(downloadAnchor);
    downloadAnchor.click();
    downloadAnchor.remove();
  };

  return (
    <div className="max-w-5xl mx-auto p-4 md:p-6 space-y-6 text-slate-100 animate-in fade-in slide-in-from-bottom-3 duration-300">
      {/* Top Banner */}
      <div className="bg-gradient-to-r from-boardroom-900 via-boardroom-850 to-indigo-950/60 border border-slate-800 rounded-3xl p-6 md:p-8 shadow-2xl relative overflow-hidden">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-6 relative z-10">
          <div className="space-y-2">
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-emerald-500/10 text-emerald-400 border border-emerald-500/30 text-xs font-semibold">
              <Award className="w-3.5 h-3.5" /> Official Committee Consensus Report
            </div>
            <h1 className="text-3xl md:text-4xl font-extrabold text-white tracking-tight">
              {evaluation.candidateName}
            </h1>
            <p className="text-slate-400 text-sm font-medium">
              Candidate for <span className="text-white font-semibold">{evaluation.targetRole}</span>
            </p>
          </div>

          {/* Big Decision Badge & Score */}
          <div className="flex items-center gap-4">
            <div className="text-center px-5 py-3 rounded-2xl bg-boardroom-900 border border-slate-800">
              <span className="text-xs text-slate-400 uppercase tracking-wider font-bold">Overall Score</span>
              <div className="text-3xl font-black text-white mt-0.5">
                {evaluation.overallScore}<span className="text-sm text-slate-500 font-normal">/100</span>
              </div>
            </div>

            <div className={`px-6 py-4 rounded-2xl border text-center shadow-lg ${getDecisionBadge(evaluation.hiringDecision)}`}>
              <span className="text-[10px] uppercase tracking-wider font-black block opacity-80">Final Verdict</span>
              <span className="text-xl md:text-2xl font-black">{evaluation.hiringDecision}</span>
            </div>
          </div>
        </div>

        {/* Executive Summary */}
        <div className="mt-6 pt-5 border-t border-slate-800/80">
          <h4 className="text-xs font-bold uppercase tracking-wider text-slate-400 mb-1.5 flex items-center gap-1.5">
            <Star className="w-3.5 h-3.5 text-amber-400" /> Executive Committee Consensus
          </h4>
          <p className="text-sm text-slate-200 leading-relaxed">
            {evaluation.consensusSummary}
          </p>
        </div>
      </div>

      {/* 4 Rubric Dimensions Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {Object.entries(evaluation.dimensions).map(([key, dim]) => (
          <div
            key={key}
            className="bg-boardroom-900 border border-slate-800 rounded-2xl p-5 space-y-3 shadow-lg hover:border-slate-700 transition-colors"
          >
            <div className="flex items-center justify-between">
              <h3 className="text-sm font-bold text-white">{dim.name}</h3>
              <span className="text-xs font-mono font-bold px-2 py-0.5 rounded bg-indigo-950 text-indigo-300 border border-indigo-800/60">
                {dim.score} / {dim.maxScore}
              </span>
            </div>

            {/* Score Bar */}
            <div className="w-full h-2 bg-boardroom-800 rounded-full overflow-hidden">
              <div
                className="h-full bg-gradient-to-r from-indigo-500 to-emerald-400 rounded-full transition-all duration-500"
                style={{ width: `${(dim.score / dim.maxScore) * 100}%` }}
              />
            </div>

            <p className="text-xs text-slate-300 leading-relaxed">
              {dim.feedback}
            </p>
          </div>
        ))}
      </div>

      {/* Strengths & Growth Areas */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {/* Key Strengths */}
        <div className="bg-boardroom-900 border border-emerald-950/60 rounded-2xl p-5 space-y-3 shadow-lg">
          <h3 className="text-xs font-bold uppercase tracking-wider text-emerald-400 flex items-center gap-2">
            <CheckCircle className="w-4 h-4" /> Key Candidate Strengths
          </h3>
          <ul className="space-y-2">
            {evaluation.keyStrengths.map((st, i) => (
              <li key={i} className="text-xs text-slate-300 flex items-start gap-2">
                <span className="text-emerald-400 mt-0.5 font-bold">✓</span>
                <span>{st}</span>
              </li>
            ))}
          </ul>
        </div>

        {/* Growth Areas */}
        <div className="bg-boardroom-900 border border-amber-950/60 rounded-2xl p-5 space-y-3 shadow-lg">
          <h3 className="text-xs font-bold uppercase tracking-wider text-amber-400 flex items-center gap-2">
            <AlertTriangle className="w-4 h-4" /> Calibration & Growth Areas
          </h3>
          <ul className="space-y-2">
            {evaluation.growthAreas.map((gr, i) => (
              <li key={i} className="text-xs text-slate-300 flex items-start gap-2">
                <span className="text-amber-400 mt-0.5 font-bold">→</span>
                <span>{gr}</span>
              </li>
            ))}
          </ul>
        </div>
      </div>

      {/* Individual Interviewer Votes */}
      <div className="bg-boardroom-900 border border-slate-800 rounded-2xl p-5 space-y-4 shadow-lg">
        <h3 className="text-xs font-bold uppercase tracking-wider text-slate-300">
          Individual Interviewer Votes & Verdicts
        </h3>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
          {Object.entries(evaluation.interviewerVotes).map(([agentKey, vote]) => {
            const agent = INTERVIEWERS[agentKey as keyof typeof INTERVIEWERS];
            if (!agent) return null;
            return (
              <div key={agentKey} className="bg-boardroom-850 border border-slate-800/80 rounded-xl p-4 space-y-2">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <div className={`w-6 h-6 rounded-md ${agent.avatarBg} text-white font-bold flex items-center justify-center text-[10px]`}>
                      {agent.name.charAt(0)}
                    </div>
                    <span className="text-xs font-bold text-white">{agent.name}</span>
                  </div>
                  <span className={`text-[10px] font-bold px-2 py-0.5 rounded border ${getDecisionBadge(vote.stance)}`}>
                    {vote.stance}
                  </span>
                </div>
                <p className="text-xs text-slate-300 italic">
                  "{vote.verdict}"
                </p>
              </div>
            );
          })}
        </div>
      </div>

      {/* Action Footer */}
      <div className="flex flex-wrap items-center justify-between gap-4 pt-4 border-t border-slate-800">
        <button
          onClick={onRestart}
          className="px-5 py-2.5 rounded-xl bg-boardroom-850 border border-slate-700 hover:border-slate-600 text-slate-300 hover:text-white text-xs font-semibold flex items-center gap-2 transition-all"
        >
          <RotateCcw className="w-3.5 h-3.5" />
          <span>Start New Interview Session</span>
        </button>

        <div className="flex items-center gap-3">
          <button
            onClick={handleCopyMarkdown}
            className="px-4 py-2.5 rounded-xl bg-boardroom-850 border border-slate-700 hover:border-indigo-500/50 text-indigo-300 text-xs font-semibold flex items-center gap-2 transition-all"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Share2 className="w-3.5 h-3.5" />}
            <span>{copied ? 'Copied Markdown!' : 'Copy Markdown Report'}</span>
          </button>

          <button
            onClick={handleDownloadJSON}
            className="px-5 py-2.5 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-bold flex items-center gap-2 shadow-lg shadow-indigo-500/20 transition-all"
          >
            <Download className="w-3.5 h-3.5" />
            <span>Download JSON Scorecard</span>
          </button>
        </div>
      </div>
    </div>
  );
};
